name: values__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 类别值
multiple: false
omit: false
readonly: false
reference_to: cc_category_spec__c
required: false
searchable: false
sort_no: 230
sortable: false
type: lookup
