name: product_media__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品媒体
omit: false
readonly: false
reference_to: cc_product_media__c
required: false
searchable: false
sort_no: 120
sortable: false
type: master_detail
write_requires_master_read: false
