name: product_media_source__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品媒体来源
multiple: false
omit: false
options:
  - label: 附件
    value: attachment
  - label: 静态资源
    value: Static_Resource
  - label: URL
    value: url
readonly: false
required: false
searchable: false
sort_no: 230
sortable: false
type: select
