name: productlistnamert__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品列表显示名称
omit: false
readonly: false
required: false
searchable: false
sort_no: 360
sortable: false
type: html
