name: product__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品
multiple: false
omit: false
readonly: false
reference_to: produce__c
required: false
searchable: false
sort_no: 140
sortable: false
type: lookup
