name: product__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品项目
multiple: false
omit: false
readonly: false
reference_to: cc_produce__c
required: false
searchable: false
sort_no: 120
sortable: false
type: lookup
