name: product_options__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品类别
multiple: false
omit: false
readonly: false
reference_to: cc_product_category__c
required: false
searchable: false
sort_no: 490
sortable: false
type: lookup
