name: product_weight__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 产品重量
omit: false
precision: 10
readonly: false
required: false
scale: 2
searchable: false
sort_no: 370
sortable: false
type: number
